//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.0
//     from Assets/CustomInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CustomInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CustomInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CustomInput"",
    ""maps"": [
        {
            ""name"": ""MenuSystem"",
            ""id"": ""938b134b-e15a-4346-8b52-b77f06429cd4"",
            ""actions"": [
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""ece85ec8-17d4-4790-b742-fba54eb77a26"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fly"",
                    ""type"": ""Button"",
                    ""id"": ""e472a9e7-f523-40e0-a007-81d5cb3f5ce8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sink"",
                    ""type"": ""Button"",
                    ""id"": ""65bf77c4-5766-4b43-ae3f-469f2b192f10"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InteractorChange"",
                    ""type"": ""Button"",
                    ""id"": ""4bcc646f-5fc3-4766-9c22-36b81f2adb41"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Change"",
                    ""type"": ""Button"",
                    ""id"": ""3dce259c-cd1a-46c8-a93b-0b6fdea07a01"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b1ccbed6-d564-45b7-a1e4-9eec73386acf"",
                    ""path"": ""<OculusTouchController>/thumbstickClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4718eb51-54f4-4fc7-808e-fe0dd75f2d30"",
                    ""path"": ""<XRController>{RightHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fly"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0deee423-ba58-497a-a6ce-160fdcd928bf"",
                    ""path"": ""<XRController>{LeftHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sink"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""769ca8cc-cc54-415a-86c5-c0659acc0147"",
                    ""path"": ""<OculusTouchController>/thumbstickClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractorChange"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2e7fb8e8-404d-454d-b22e-e31ddc6330de"",
                    ""path"": ""<XRController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Change"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MenuSystem
        m_MenuSystem = asset.FindActionMap("MenuSystem", throwIfNotFound: true);
        m_MenuSystem_Menu = m_MenuSystem.FindAction("Menu", throwIfNotFound: true);
        m_MenuSystem_Fly = m_MenuSystem.FindAction("Fly", throwIfNotFound: true);
        m_MenuSystem_Sink = m_MenuSystem.FindAction("Sink", throwIfNotFound: true);
        m_MenuSystem_InteractorChange = m_MenuSystem.FindAction("InteractorChange", throwIfNotFound: true);
        m_MenuSystem_Change = m_MenuSystem.FindAction("Change", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MenuSystem
    private readonly InputActionMap m_MenuSystem;
    private List<IMenuSystemActions> m_MenuSystemActionsCallbackInterfaces = new List<IMenuSystemActions>();
    private readonly InputAction m_MenuSystem_Menu;
    private readonly InputAction m_MenuSystem_Fly;
    private readonly InputAction m_MenuSystem_Sink;
    private readonly InputAction m_MenuSystem_InteractorChange;
    private readonly InputAction m_MenuSystem_Change;
    public struct MenuSystemActions
    {
        private @CustomInput m_Wrapper;
        public MenuSystemActions(@CustomInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Menu => m_Wrapper.m_MenuSystem_Menu;
        public InputAction @Fly => m_Wrapper.m_MenuSystem_Fly;
        public InputAction @Sink => m_Wrapper.m_MenuSystem_Sink;
        public InputAction @InteractorChange => m_Wrapper.m_MenuSystem_InteractorChange;
        public InputAction @Change => m_Wrapper.m_MenuSystem_Change;
        public InputActionMap Get() { return m_Wrapper.m_MenuSystem; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuSystemActions set) { return set.Get(); }
        public void AddCallbacks(IMenuSystemActions instance)
        {
            if (instance == null || m_Wrapper.m_MenuSystemActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MenuSystemActionsCallbackInterfaces.Add(instance);
            @Menu.started += instance.OnMenu;
            @Menu.performed += instance.OnMenu;
            @Menu.canceled += instance.OnMenu;
            @Fly.started += instance.OnFly;
            @Fly.performed += instance.OnFly;
            @Fly.canceled += instance.OnFly;
            @Sink.started += instance.OnSink;
            @Sink.performed += instance.OnSink;
            @Sink.canceled += instance.OnSink;
            @InteractorChange.started += instance.OnInteractorChange;
            @InteractorChange.performed += instance.OnInteractorChange;
            @InteractorChange.canceled += instance.OnInteractorChange;
            @Change.started += instance.OnChange;
            @Change.performed += instance.OnChange;
            @Change.canceled += instance.OnChange;
        }

        private void UnregisterCallbacks(IMenuSystemActions instance)
        {
            @Menu.started -= instance.OnMenu;
            @Menu.performed -= instance.OnMenu;
            @Menu.canceled -= instance.OnMenu;
            @Fly.started -= instance.OnFly;
            @Fly.performed -= instance.OnFly;
            @Fly.canceled -= instance.OnFly;
            @Sink.started -= instance.OnSink;
            @Sink.performed -= instance.OnSink;
            @Sink.canceled -= instance.OnSink;
            @InteractorChange.started -= instance.OnInteractorChange;
            @InteractorChange.performed -= instance.OnInteractorChange;
            @InteractorChange.canceled -= instance.OnInteractorChange;
            @Change.started -= instance.OnChange;
            @Change.performed -= instance.OnChange;
            @Change.canceled -= instance.OnChange;
        }

        public void RemoveCallbacks(IMenuSystemActions instance)
        {
            if (m_Wrapper.m_MenuSystemActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMenuSystemActions instance)
        {
            foreach (var item in m_Wrapper.m_MenuSystemActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MenuSystemActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MenuSystemActions @MenuSystem => new MenuSystemActions(this);
    public interface IMenuSystemActions
    {
        void OnMenu(InputAction.CallbackContext context);
        void OnFly(InputAction.CallbackContext context);
        void OnSink(InputAction.CallbackContext context);
        void OnInteractorChange(InputAction.CallbackContext context);
        void OnChange(InputAction.CallbackContext context);
    }
}
